### ISSUE TITLE
Why were Asyncio changes not included in the stable version?

### ISSUE THREAD

**Issue by optsing** [pysnmp/pysnmp#32]
@asyncio.coroutine was replaced with simple async in 5.0.19b1-2 but it returned in stable 5.0.19. 
This change is required to use library with Python 3.11

**Comment by omrozowicz-splunk** [comment]
Hey, the reason the change was not included in `5.0.19` is that the beta version had an issue with traps receiving. The fix was included in #33 and it will be released as a stable version in the coming days.  `5.0.19` had only documentation fixes, and we needed to release it to make it visible on PyPI.
