### ISSUE TITLE
Significant gaps on this fork/organization and possible solutions

### ISSUE THREAD

**Issue by lextm** [pysnmp/pysnmp#34]
A quick look around this fork and its related repos, I think the following issues are critical at this moment, if the goal is to keep pysnmp ecosystem sustainable,

1. The releases from this fork do not have meaningful release notes compared to the origin, so honestly speaking I don't know what has changed.
2. The release numbers (5.0.11-5.0.14) are missing for no good reasons. Such really should be avoided.
3. Pre-releases might be hidden once the stable ones are out.
4. The `v5.0` and `v5` tags are there for no good reasons.
5. Not all pysnmp projects are forked under https://github.com/pysnmp.
6. Not clear what's the missions and plans for the whole organization (after such a long period), so it is hard to build trust here.
7. Issues of the origin repo are not processed, so no traffic is clearly redirected here nor drive further development of this ecosystem.
8. The homepage was not forked so new users do not have reliable materials to get started. I already forked the web contents and hosted them at https://www.pysnmp.com as a new start, so if possible I'd like to move the repo under https://github.com/pysnmp.

I helped revive many open source projects in the past, and I'd like to see if there is any assistance needed here.

**Comment by omrozowicz-splunk** [comment]
Hi! Thanks for opening this issue, I'll tell you how the situation looks from my side.
This fork was created because we needed to fix a few things and the main Pysnmp hasn't been updated since 2019. @ryanfaircloth synced it with PyPI so we could easily update it as a dependency to the main project we worked on -> [SC4SNMP](https://github.com/splunk/splunk-connect-for-snmp). It wasn't meant to be a successor to Ilya's Pysnmp from the beginning, but we have a working CI and had a bunch of PRs from community members. Probably this fork looks the most active among all of the others and that made Ryan advertise it on Ilya's Pysnmp repo. 

I can work on every maintenance thing you mentioned (thank you, btw!), clean up unnecessary releases, hide pre-releases, and the gap with versioning you noticed created while we were fixing the CI (not sure I can do anything about it now, only I can avoid it in the future). My biggest problem though is that I lack sanity tests. The only thing I have is the SC4SNMP's integration tests pipeline, where I have some of the pysnmp's functionalities (like v2,v3 polling, and traps), which is better than nothing, but it doesn't cover all of the functionalities we have.

`Issues of the origin repo are not processed, so no traffic is clearly redirected here nor drive further development of this ecosystem.` - I'm totally open to adding more admins to this repo and putting it more into the hands of the community, alone I don't think I can handle fixing the issues and actively working on further development, as long as it doesn't align in SC4SNMP.

**Comment by ryanfaircloth** [comment]
@lextm you raise valid points I appreciate your feedback our original plan was to return the changes we made to the upstream not to fork and along the way we made some mistakes that had lasting consequences.  Line by line response below. As we started to consume the original project we had a small amount of communication with the original author however he fell ill and disappeared there was a substantial amount of time we waited hoping for this best health.

The release numbers (5.0.11-5.0.14) are missing for no good reasons. Such really should be avoided.
* Agree going forward the project will require semantic commit PRs to solve this problem

Pre-releases might be hidden once the stable ones are out.
* This is a nit but a solvable nit. If someone wanted to raise a PR to automate hiding pre-releases on tag with a semver of a release we would take it

The v5.0 and v5 tags are there for no good reasons.
* I Have a use for these tags if you don't thats fine

Not all pysnmp projects are forked under https://github.com/pysnmp.
* Some of the pysnmp projects were not used/release we only forked what we have reason to need if someone comes along and finds a use and wants to help maintain thats something we would welcome.

Not clear what's the missions and plans for the whole organization (after such a long period), so it is hard to build trust here.
* For the current maintainers use pysnmp is only used for traps/get/bulkget operations. There is great functionality in this library we don't exploit so we don't have a maintainer for that code. We have made efforts to update python syntax for newer python runtimes. Essentially this seems to be feature complete if there is a need and contributor for a solution for that need it would be welcome.

Issues of the origin repo are not processed, so no traffic is clearly redirected here nor drive further development of this ecosystem.
* We don't have anyone with time available to keep up with issues we also don't have access to the original org/repo so we can't do any more than comment

The homepage was not forked so new users do not have reliable materials to get started. I already forked the web contents and hosted them at https://www.pysnmp.com/ as a new start, so if possible I'd like to move the repo under https://github.com/pysnmp.
* Thats great I considered this at one point but the domain was not expired and I never looked again glad you did it. Would you like to move forward and maintain that. Can we host with github pages to avoid costs? I'd like to discuss this privately

**Comment by lextm** [comment]
@ryanfaircloth I will write an email to you to go through the non-technical parts first as you requested. Then we can go back here to see what can be published as a roadmap for collaboration.

**Comment by lextm** [comment]
Post core steps of the plan and progress to https://github.com/etingof/pysnmp/issues/429 to engage more users.
